project_id = "yjhqfgbtennfynlodftq"


[functions.notify-product-available]
verify_jwt = false

[functions.sync-order-to-sheets]
verify_jwt = false

[functions.analyze-payment-proof]
verify_jwt = false

[functions.auto-complete-orders]
verify_jwt = false

[functions.sync-images-to-storage]
verify_jwt = false

[functions.update-affiliate-commission]
verify_jwt = false

[functions.check-expiring-products]
verify_jwt = false
